### ISSUE TITLE
When Recipe Recursion Depth is greater than 0 or set to -1, the OnCraftHook event for items will be unconditionally triggered.

### ISSUE THREAD

**Issue by hocha113** [blushiemagic/MagicStorage#275]
If the value of `MagicStorageConfig.RecipeRecursionDepth` is not 0, issues may occur. For example, if it is set to 1, clicking on any item in the CraftingAccess UI will cause all crafting events to be triggered once. If `MagicStorageConfig.RecipeRecursionDepth` is -1, a callback event will be triggered once. I suspect this is related to `OnCraftHooks`. Perhaps the problem lies in the lack of proper conditional checks in `RecursiveRecipe.ModifyCraftingTree`?

**Comment by absoluteAquarian** [comment]
The current _public_ implementation of the recursion crafting logic calls `RecipeLoader.OnCraft()` during the simulations in order to catch items "dropped" by crafting recipes.  This, however, leads to what you've observed where _any_ OnCraft logic ends up running just from opening the UI.  It has since been changed to use a separate opt-in system for "recipe craft drops" and only calling OnCraft during the actual crafts.

**Comment by hocha113** [comment]
Okay, great fix! Additionally, I submitted a pull request for a localization translation. If you don't have a better Chinese translation for now, you can take a look at this submission

**Comment by hocha113** [comment]
> The current _public_ implementation of the recursion crafting logic calls `RecipeLoader.OnCraft()` during the simulations in order to catch items "dropped" by crafting recipes. This, however, leads to what you've observed where _any_ OnCraft logic ends up running just from opening the UI. It has since been changed to use a separate opt-in system for "recipe craft drops" and only calling OnCraft during the actual crafts.

Okay, great fix! Additionally, I submitted a pull request for a localization translation. If you don't have a better Chinese translation for now, you can take a look at this submission
