### ISSUE TITLE
[Suggestion] Add Ctrl-Backspace Support to the Search Bar

### ISSUE THREAD

**Issue by HeyItsMcKay** [blushiemagic/MagicStorage#38]

**Comment by homemmakako** [comment]
I would suggest using right click to erase all text from the search bar, instead of ctrl+backspace for erasing an entire word. Since you need to move your mouse to the search bar it is more convenient (I have play modded minecraft for a while now, and many mods have both options, no one never uses the  backspace one though 😝)
