### ISSUE TITLE
Suggestion: Add quick stack button

### ISSUE THREAD

**Issue by SuperCuber** [blushiemagic/MagicStorage#40]
Vanilla stoarge items have Loot all, Deposit all, Quick stack, Restock, Sort items

Currently we only have deposit all and sort items, would love to see others. (Loot all would be useful if moving the system for example)

**Comment by whismerhill** [comment]
AFAIK if you favorite items, the rest can be "deposited all" pretty much the same result as quick stack
since the vanilla quickstack action is mostly made so you can quickstack through multiple chests

**Comment by SuperCuber** [comment]
@whismerhill yes that works but feels like a workaround

**Comment by whismerhill** [comment]
so programmatically : 
1. for each non-favorite item through player inventory
2. loop through the magic storage to look up a matching item
3. if found put it in storage
4. go back to 1 for next item

**Comment by SuperCuber** [comment]
@whismerhill https://owo.whats-th.is/cb6dcf.png

**Comment by SuperCuber** [comment]
Could also implement the special behavior of piggy bank where it also stacks coins. That would eliminate the need to keep a piggy bank near your storage access points.

**Comment by whismerhill** [comment]
@SuperCuber this text & layout doesn't fit the current interface of magic storage where would you place that ???

**Comment by SuperCuber** [comment]
No idea, my suggestion is to try to make it similar to the regular storage

**Comment by whismerhill** [comment]
so hum
First I'm not the project manager, hence my opinion might not really matter.

Second, now that this is out of the way, my opinion is : your suggestion is nice & all but not enough thought went into it, hence I fail to see how to even use your idea as it is.
Furthermore, redoing the whole UI to make it look like regular storage doesn't seem particularly great due to amount of work + because due to quantity of items we need better filtering system over vanilla storage.

Conclusion, I appreciate your input but idea seems unusable as is + doesn't bring much to the table since  workarounds already exists.

suggestion for improving this issue: take screenshots of existing magic storage assets and use paint/gimp/creativity to work out buttons schemes & layouts

**Comment by OthmanEmpire** [comment]
But what about in the case where there are multiple independent storage systems existing? The deposit all strategy no longer works in this case. Any suggestions for such a scenario?

**Comment by Ttamage** [comment]
I think a quick stack option would make magic storage the most perfect storage option in mod Terraria.  I would like to be able to run by and do the old quick storage sweep as I unload my bulk of random items collected while running about.  I typically have about 30% of my inventory as items I permanently have in my inventory so the deposit all option for items when I use magic storage is inconvenient.  And opening magic storage manually and individually selecting and depositing the 20 or 30 items I want to deposit every time I deposit them is a Time waster.  If I have 850 dirt in my inventory I don't want to open the menu select dirt in my inventory and stack it manually when quick stack is such a convenient option on traditional chests.  Literally with quick stack I run through my base open up my menu and spam the quick stack option to offload all of my inventory items into chest that already have those items.  When I have an item I don't want to quick stack like health potions I typically keep that in the piggy bank or in a chest outside of my base so it doesn't accidentally get swapped.  For example the magic mirror is an item I keep in a separate chest far away from my base so that I don't accidentally quick stack my magic mirror out of my inventory and then get stranded somewhere when exploring in the game.

**Comment by Ttamage** [comment]
Favorite an item is something I'll have to experiment with I've never used that option before.
